###################################################################
# stream2segment config file to tune the functionality.
# IMPORTANT: THIS IS A YAML FILE, IF YOU ARE NEW TO IT BEFORE EDITING SEE e.g.:
# http://symfony.com/doc/current/components/yaml/yaml_format.html
# or
# http://docs.ansible.com/ansible/YAMLSyntax.html
###################################################################

# channels (identifies short period, accelerometers but also broad band):
channels: # sampling rate (hight to low) / type of data (broadband etcetera)
 - "HH?"
 - 'SH?'
 - 'BH?'
 - 'HN?'
 - 'SN?'
 - 'BN?'
# - 'HL?'
# - 'SL?'
# - 'BL?'

# Include only two datacentres to test. You can change to the full
# set of datacentres as soon as you think it's working.
datacenters:
 GFZ: 'http://geofon.gfz-potsdam.de/fdsnws'
 ETH: 'http://arclink.ethz.ch/fdsnws'
# ODC: 'http://www.orfeus-eu.org/fdsnws'
# RESIF: 'http://ws.resif.fr/fdsnws'
# INGV: 'http://webservices.rm.ingv.it/fdsnws'
# BGR: 'http://eida.bgr.de/fdsnws'
# LMU: 'http://erde.geophysik.uni-muenchen.de/fdsnws'
# IPGP: 'http://eida.ipgp.fr/fdsnws'
# NIEP: 'http://eida-sc3.infp.ro/fdsnws'
# KOERI: 'http://eida.koeri.boun.edu.tr/fdsnws'

# other sesmic specific parameters
eventws: 'http://seismicportal.eu/fdsnws/event/1/'
minmag: 3.0
minlat: 30.0
maxlat: 80.0
minlon: -10.0
maxlon: 60.0
ptimespan:
 - 1.0 # minutes before a P wave arrival time
 - 3.0 # minutes after a P wave arrival time
#search radius parameters (mag_min, max_max, dist_min, dist_max)
search_radius_args:
 - 3 # min magnitude
 - 7 # max magnitude
 - 1 # min distance (deg)
 - 5 # max distance (deg)

# these are optional, missing defaults to start:yesterday at midnight, today at midnight
#start: 2016-04-23T00:00:00
#end: 2016-04-23T11:00:00

# program specific parameters:

# outpath: specify a database file name
# Usually, it is a sqlite database, in which case just write the path to your local file
# PREPENED with 'sqlite:///' (e.g., 'sqlite:////home/my_folder/db.sqlite')
# Otherwise, the syntax is:
# dialect+driver://username:password@host:port/database
# (for info see: http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls)
outpath: 'sqlite:///./mydb.sqlite'  # '/tmp/mseeds/'
